const translations={
  ar:{
    login:'دخول',latest_products:'أحدث المعروضات',loading:'جاري التحميل...',inbox_title:'الرسائل الواردة',guest_title:'أنت زائر',guest_msg:'سجل الدخول لإدارة إعلاناتك.',add_ad_btn:'إضافة إعلان جديد',my_ads:'إعلاناتي',nav_home:'الرئيسية',nav_chats:'المحادثات',nav_profile:'حسابي',sell_new_item:'بيع منتج جديد',upload_text:'اضغط لاختيار الصور',upload_hint:'حد أقصى 3 صور - حجم صغير',label_prod_name:'اسم المنتج',label_category:'القسم',label_price:'السعر بالدولار ($)',top_pi_notice:'يتم تحديث سعر Pi لحظيًا من OKX',label_desc:'الوصف',label_views:'المشاهدات:',publish_btn:'نشر الإعلان',msg_placeholder:'اكتب رسالة...',promoted_badge:'مميز',message_seller:'مراسلة البائع',promote_ad_btn:'تمييز الإعلان',promoted_until:'مميز حتى',delete_btn:'حذف',confirm_delete:'هل أنت متأكد من الحذف؟',no_products:'لا توجد منتجات',no_messages:'لا توجد رسائل',toast_login_first:'يجب تسجيل الدخول أولًا',toast_fill_data:'يرجى إكمال البيانات المطلوبة',toast_success_add:'تم إرسال الإعلان للمراجعة',toast_send_fail:'فشل الإرسال',toast_max_images:'الحد الأقصى 3 صور',banned_title:'حساب محظور',banned_msg:'تم إيقاف حسابك لمخالفة شروط الاستخدام.',ph_prod_name:'مثال: iPhone 13 Pro',ph_desc:'اكتب تفاصيل المنتج وحالته...',ph_price_usd:'مثال: 10.50',cat_all:'الكل',cat_cars:'سيارات',cat_electronics:'إلكترونيات',cat_phones:'هواتف',cat_fashion:'ملابس',cat_home:'منزل',cat_other:'أخرى',select_cat:'اختر القسم المناسب',btn_back:'رجوع',label_joined:'انضم:',label_total_ads:'إعلانات:',ph_search:'ابحث عن منتج...',label_country:'الدولة',label_state:'المنطقة / المحافظة',promote_title:'اختر خطة التمييز',plan_1:'باقة عادية - صالحة 3 أيام',plan_5:'باقة مميزة - صالحة أسبوع',plan_10:'باقة فوق المميزة - صالحة أسبوعين',stat_views:'المشاهدات',stat_chats:'المحادثات',feat_gold:'شارة ذهبية',feat_priority:'أولوية الظهور',feat_high_priority:'أولوية عالية',feat_save:'ظهور في القمة',link_privacy:'سياسة الخصوصية',link_terms:'شروط الخدمة',price_waiting:'في انتظار سعر Pi',telegram_link:'ربط بوت تيليجرام',telegram_linked:'تم الربط',telegram_opening:'جاري فتح تيليجرام...',telegram_start_hint:'افتح تيليجرام واضغط Start داخل البوت ثم ارجع للموقع',telegram_token_error:'حدث خطأ في إنشاء كود الربط',self_message_error:'لا يمكنك مراسلة نفسك',no_ads_title:'لا توجد إعلانات',no_ads_msg:'ابدأ بإضافة إعلانك الأول!',promotion_price_note:'يتم تحديث مقدار Pi تلقائيًا حسب سعر PI/USDT اللحظي من OKX وقت الدفع.'
  },
  en:{
    login:'Login',latest_products:'Latest Products',loading:'Loading...',inbox_title:'Inbox',guest_title:'Guest User',guest_msg:'Login to manage your ads.',add_ad_btn:'Post New Ad',my_ads:'My Ads',nav_home:'Home',nav_chats:'Chats',nav_profile:'Profile',sell_new_item:'Sell New Item',upload_text:'Tap to upload images',upload_hint:'Max 3 images - Small size',label_prod_name:'Product Name',label_category:'Category',label_price:'Price in USD ($)',top_pi_notice:'Pi price is updated live from OKX',label_desc:'Description',label_views:'Views:',publish_btn:'Publish Ad',msg_placeholder:'Type a message...',promoted_badge:'Promoted',message_seller:'Message Seller',promote_ad_btn:'Promote Ad',promoted_until:'Promoted until',delete_btn:'Delete',confirm_delete:'Are you sure to delete?',no_products:'No products found',no_messages:'No messages',toast_login_first:'Login required first',toast_fill_data:'Please fill all required fields',toast_success_add:'Ad sent for review',toast_send_fail:'Failed to send',toast_max_images:'Max 3 images allowed',banned_title:'Account Banned',banned_msg:'Your account is suspended due to violations.',ph_prod_name:'Ex: iPhone 13 Pro',ph_desc:'Describe item details...',ph_price_usd:'Ex: 10.50',cat_all:'All',cat_cars:'Cars',cat_electronics:'Electronics',cat_phones:'Phones',cat_fashion:'Fashion',cat_home:'Home',cat_other:'Other',select_cat:'Select Category',btn_back:'Back',label_joined:'Joined:',label_total_ads:'Total Ads:',ph_search:'Search products...',label_country:'Country',label_state:'State / Province',promote_title:'Choose Promotion Plan',plan_1:'Standard Package - valid for 3 days',plan_5:'Featured Package - valid for 1 week',plan_10:'Top Featured Package - valid for 2 weeks',stat_views:'Views',stat_chats:'Chats',feat_gold:'Golden Badge',feat_priority:'Standard Priority',feat_high_priority:'High Priority',feat_save:'Top placement',link_privacy:'Privacy Policy',link_terms:'Terms of Service',price_waiting:'Waiting for Pi price',telegram_link:'Link Telegram Bot',telegram_linked:'Linked',telegram_opening:'Opening Telegram...',telegram_start_hint:'Open Telegram, press Start, then return to the site',telegram_token_error:'Could not create link token',self_message_error:'You cannot message yourself',no_ads_title:'No ads yet',no_ads_msg:'Start by adding your first ad!',promotion_price_note:'Pi amount updates automatically using the live PI/USDT price from OKX at payment time.'
  }
};
const CATEGORIES_CONFIG=[{id:'all',key:'cat_all',icon:'fa-layer-group'},{id:'cars',key:'cat_cars',icon:'fa-car'},{id:'electronics',key:'cat_electronics',icon:'fa-laptop'},{id:'phones',key:'cat_phones',icon:'fa-mobile-screen'},{id:'fashion',key:'cat_fashion',icon:'fa-shirt'},{id:'home',key:'cat_home',icon:'fa-couch'},{id:'other',key:'cat_other',icon:'fa-box'}];function t(k){return translations[currentLang][k]||translations.en[k]||k}
function updateLanguage(){safeSetText('langText',currentLang==='ar'?'EN':'AR');document.documentElement.lang=currentLang;document.documentElement.dir=currentLang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-i18n]').forEach(e=>{const k=e.getAttribute('data-i18n');if(translations[currentLang][k])e.innerHTML=translations[currentLang][k]});safeSetPlaceholder('addName',t('ph_prod_name'));safeSetPlaceholder('addDesc',t('ph_desc'));safeSetPlaceholder('addPrice',t('ph_price_usd'));safeSetPlaceholder('msgInput',t('msg_placeholder'));safeSetPlaceholder('searchInput',t('ph_search'));initCategories();renderPromotionPlanPrices();updatePiPriceBar();if(globalProducts.length>0)renderProducts();refreshTelegramButton(false)}function toggleLanguage(){currentLang=currentLang==='ar'?'en':'ar';localStorage.setItem('lang',currentLang);updateLanguage()}
function showToast(messageKey,type='success'){const c=el('toast-container');const toast=document.createElement('div');toast.className=`toast ${type}`;const icons={success:'fa-check-circle',error:'fa-circle-exclamation',warning:'fa-triangle-exclamation'},colors={success:'#10B981',error:'#EF4444',warning:'#F59E0B'};const msg=translations[currentLang][messageKey]||messageKey;toast.innerHTML=`<div class="toast-icon" style="color:${colors[type]||colors.success}"><i class="fa-solid ${icons[type]||icons.success}"></i></div><span class="toast-msg"></span>`;toast.querySelector('.toast-msg').innerText=msg;c.appendChild(toast);setTimeout(()=>{toast.style.opacity='0';setTimeout(()=>toast.remove(),300)},4000)}


